# Generated by Django 6.0.1 on 2026-03-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('method', models.CharField(choices=[('STANDARD', 'Giao hàng tiêu chuẩn'), ('EXPRESS', 'Giao hàng nhanh'), ('PICKUP', 'Nhận tại cửa hàng')], default='STANDARD', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('SHIPPED', 'Đã giao'), ('DELIVERED', 'Đã nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
