# Generated by Django 6.0.1 on 2026-03-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ'), ('BANK', 'Chuyển khoản')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('COMPLETED', 'Đã thanh toán'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
